spring:
  application:
    name:
      SsoDemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liU3lzi8sjhxAGw8
            client-secret: ac6842a01a058a6dbbcebb2f7b74efde4dfc1519
            redirect-uri: http://localhost:8080/login/oauth2/code/github
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml

