spring:
  application:
    name:
      SsoDemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 123
            client-secret: 456
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml

